### Recuperar todos los usuarios
GET http://localhost:3000/users

### Recuperar un usuario
GET http://localhost:3000/users/3

### Crear un nuevo usuario
POST http://localhost:3000/users

Content-Type: application/json


{
    "name": "John Doe",
    "email": "johndoe@example.com"

}

### Actualizar un usuario
PUT http://localhost:3000/users/1

Content-Type: application/json


{
    "name": "Jane Doe",
    "email": "dsadsa",
    "password": "123456",
    "role": "admin",
}

### Eliminar un usuario

